CREATE TABLE IF NOT EXISTS properties (
    property_id TEXT PRIMARY KEY,
    listing_id TEXT NOT NULL,
    source TEXT NOT NULL,
    listing_url TEXT NOT NULL,
    date_collected TEXT NOT NULL,
    last_updated TEXT,
    status TEXT,

    neighborhood TEXT,
    superquadra TEXT,
    block TEXT,
    street TEXT,
    cep TEXT,
    latitude REAL,
    longitude REAL,

    area_m2 REAL,
    bedrooms INTEGER,
    bathrooms INTEGER,
    garage_spaces INTEGER,
    floor INTEGER,
    elevator INTEGER,
    building_age INTEGER,
    furnished INTEGER,
    balcony INTEGER,
    storage INTEGER,
    air_conditioning INTEGER,

    asking_price REAL,
    offer_price REAL,
    estimated_fair_value REAL,
    closing_costs REAL,
    renovation_budget REAL,
    condo_fee REAL,
    iptu REAL,
    insurance REAL,

    expected_rent REAL,
    conservative_rent REAL,
    optimistic_rent REAL,
    rent_m2 REAL,
    expected_vacancy REAL,
    airbnb_estimate REAL,

    down_payment REAL,
    loan_amount REAL,
    interest_rate REAL,
    loan_term_years INTEGER,
    mortgage_payment REAL,
    monthly_cash_flow REAL,

    gross_yield REAL,
    net_yield REAL,
    cash_on_cash REAL,
    irr REAL,
    npv REAL,
    payback_years REAL,
    mortgage_coverage REAL,
    investment_score INTEGER,
    recommendation TEXT
);